### ISSUE TITLE
Error after conversion to pdf format

### ISSUE THREAD

**Issue by Raizelian** [ale00/Scuolabook-Downloader-2#2]
As in title, output is such:

```
Converting images to pdf format...
'62ae05baf7f172c64b6c7d690e8c4e03.pdf' created!

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 658, in read_images
    imgdata = Image.open(im)
  File "/home/Raizelian/.local/lib/python3.6/site-packages/PIL/Image.py", line 2959, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f5addd09f10>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "working.py", line 66, in <module>
    pdf_bytes = img2pdf.convert([cache + filename + ".jpg"])
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 1023, in convert
    in read_images(rawdata, colorspace, first_frame_only):
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 663, in read_images
    "PIL: error reading image: %s" % e)
img2pdf.ImageOpenError: cannot read input image (not jpeg2000). PIL: error reading image: cannot identify image file <_io.BytesIO object at 0x7f5addd09f10>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 658, in read_images
    imgdata = Image.open(im)
  File "/home/Raizelian/.local/lib/python3.6/site-packages/PIL/Image.py", line 2959, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f5addc2e678>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "working.py", line 68, in <module>
    pdf_bytes = img2pdf.convert(open(cache + filename + ".jpg","rb").read())
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 1023, in convert
    in read_images(rawdata, colorspace, first_frame_only):
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 663, in read_images
    "PIL: error reading image: %s" % e)
img2pdf.ImageOpenError: cannot read input image (not jpeg2000). PIL: error reading image: cannot identify image file <_io.BytesIO object at 0x7f5addc2e678>
```

I'd love to see this working since it's a truly useful script.

**Comment by alessionossa** [comment]
Hello, sorry for the late response. Does the error happens with any book?

**Comment by alessionossa** [comment]
Closing because there's no follow-up.
